spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_advanced
    username: root
    password: 1234abcd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true